# Student Performance Dataset EDA Practice
Basic to Intermediate Pandas Questions

## Q1. Import pandas library

In [5]:
import pandas as pd

## Q2. Read CSV file

In [12]:
df = pd.read_excel('student_performance_dataset_1.csv.xlsx')
df

,student_id,age,gender,grade_level,study_hours_per_day,uses_ai,ai_usage_time_minutes,ai_tools_used,ai_usage_purpose,ai_dependency_score,...,concept_understanding_score,study_consistency_index,improvement_rate,sleep_hours,social_media_hours,tutoring_hours,class_participation_score,final_score,passed,performance_category
0,1,20,Female,1st Year,2.5,1,170,NaN,Exam Prep,10,...,4,9,8.1,7.2,1.5,4.6,6,36.8,0,Low
1,2,17,Male,12th,3.4,1,123,NaN,Notes,4,...,8,8.5,13.8,7.6,5.1,2.7,6,65.5,1,Medium
2,3,24,Male,3rd Year,0.8,0,35,Copilot,Doubt Solving,8,...,7,2.1,39.1,5.7,0.2,4.0,3,66.3,1,Medium
3,4,21,Female,12th,4.4,0,45,ChatGPT+Gemini,Notes,3,...,5,6.7,25.2,8.2,4.2,2.9,2,69.5,1,Medium
4,5,18,Other,3rd Year,3.5,1,21,ChatGPT+Gemini,Coding,2,...,5,5.4,2.7,8.7,0.2,2.9,2,49.7,1,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,7996,23,Male,3rd Year,3.0,0,178,Gemini,NaN,6,...,5,8.1,19.2,8.3,1.9,1.0,10,49.7,1,Low
7996,7997,21,Other,1st Year,3.3,0,63,Claude,Exam Prep,10,...,6,5.7,3.0,5.0,1.3,2.9,5,58.4,1,Medium
7997,7998,24,Male,3rd Year,1.6,0,113,ChatGPT,Coding,5,...,6,4.5,-18.0,5.0,3.5,0.1,9,69.1,1,Medium
7998,7999,22,Female,2nd Year,5.5,0,21,Copilot,Coding,5,...,8,3.4,-19.1,4.7,5.9,0.4,7,49.2,1,Low
7999,8000,15,Male,12th,4.6,0,42,NaN,NaN,9,...,6,9.7,-4.9,9.0,2.9,2.1,5,69.7,1,Medium

## Q3. Display first 10 records

In [13]:
df.head(10)

,student_id,age,gender,grade_level,study_hours_per_day,uses_ai,ai_usage_time_minutes,ai_tools_used,ai_usage_purpose,ai_dependency_score,...,concept_understanding_score,study_consistency_index,improvement_rate,sleep_hours,social_media_hours,tutoring_hours,class_participation_score,final_score,passed,performance_category
0,1,20,Female,1st Year,2.5,1,170,NaN,Exam Prep,10,...,4,9,8.1,7.2,1.5,4.6,6,36.8,0,Low
1,2,17,Male,12th,3.4,1,123,NaN,Notes,4,...,8,8.5,13.8,7.6,5.1,2.7,6,65.5,1,Medium
2,3,24,Male,3rd Year,0.8,0,35,Copilot,Doubt Solving,8,...,7,2.1,39.1,5.7,0.2,4.0,3,66.3,1,Medium
3,4,21,Female,12th,4.4,0,45,ChatGPT+Gemini,Notes,3,...,5,6.7,25.2,8.2,4.2,2.9,2,69.5,1,Medium
4,5,18,Other,3rd Year,3.5,1,21,ChatGPT+Gemini,Coding,2,...,5,5.4,2.7,8.7,0.2,2.9,2,49.7,1,Low
5,6,20,Male,1st Year,5.1,1,34,Copilot,Coding,10,...,9,8,13.4,5.5,3.7,2.1,4,77.9,1,High
6,7,23,Female,1st Year,2.0,1,112,ChatGPT+Gemini,NaN,8,...,9,9.6,3.7,5.8,1.6,3.4,5,82.2,1,High
7,8,16,Male,3rd Year,5.5,0,174,ChatGPT,Homework,4,...,6,4.3,13.2,6.0,0.4,2.5,6,52.7,1,Medium
8,9,20,Female,10th,6.0,1,32,Copilot,NaN,9,...,9,7.8,18.8,5.4,1.6,4.2,4,81.7,1,High
9,10,24,Female,1st Year,5.6,0,140,NaN,Doubt Solving,3,...,7,2.9,38.5,7.2,0.7,4.6,1,66.7,1,Medium

## Q4. Display last 10 records

In [ ]:
df.tail(10)

,student_id,age,gender,grade_level,study_hours_per_day,uses_ai,ai_usage_time_minutes,ai_tools_used,ai_usage_purpose,ai_dependency_score,...,concept_understanding_score,study_consistency_index,improvement_rate,sleep_hours,social_media_hours,tutoring_hours,class_participation_score,final_score,passed,performance_category
7990,7991,15,Male,11th,5.9,1,15,NaN,Doubt Solving,5,...,2,8.0,-9.6,5.4,1.9,3.3,8,31.7,0,Low
7991,7992,15,Female,10th,4.8,0,36,Gemini,Notes,8,...,7,3.1,3.4,7.7,3.2,3.6,10,53.4,1,Medium
7992,7993,18,Female,3rd Year,3.4,1,164,NaN,Exam Prep,10,...,8,5.1,28.3,7.3,2.2,3.5,4,73.5,1,Medium
7993,7994,23,Male,1st Year,2.9,1,134,NaN,NaN,4,...,1,1.7,16.6,6.4,5.6,4.3,5,38.1,0,Low
7994,7995,23,Male,11th,3.5,1,39,ChatGPT,Homework,4,...,5,2.1,32.4,5.1,3.6,4.3,2,39.8,0,Low
7995,7996,23,Male,3rd Year,3.0,0,178,Gemini,NaN,6,...,5,8.1,19.2,8.3,1.9,1.0,10,49.7,1,Low
7996,7997,21,Other,1st Year,3.3,0,63,Claude,Exam Prep,10,...,6,5.7,3.0,5.0,1.3,2.9,5,58.4,1,Medium
7997,7998,24,Male,3rd Year,1.6,0,113,ChatGPT,Coding,5,...,6,4.5,-18.0,5.0,3.5,0.1,9,69.1,1,Medium
7998,7999,22,Female,2nd Year,5.5,0,21,Copilot,Coding,5,...,8,3.4,-19.1,4.7,5.9,0.4,7,49.2,1,Low
7999,8000,15,Male,12th,4.6,0,42,NaN,NaN,9,...,6,9.7,-4.9,9.0,2.9,2.1,5,69.7,1,Medium

## Q5. Display shape

In [ ]:
df.shape

(8000, 26)

## Q6. Display columns

In [ ]:
df.columns

Index(['student_id', 'age', 'gender', 'grade_level', 'study_hours_per_day',
       'uses_ai', 'ai_usage_time_minutes', 'ai_tools_used', 'ai_usage_purpose',
       'ai_dependency_score', 'ai_generated_content_percentage',
       'ai_prompts_per_week', 'ai_ethics_score', 'last_exam_score',
       'assignment_scores_avg', 'attendance_percentage',
       'concept_understanding_score', 'study_consistency_index',
       'improvement_rate', 'sleep_hours', 'social_media_hours',
       'tutoring_hours', 'class_participation_score', 'final_score', 'passed',
       'performance_category'],
      dtype='object')

## Q7. Dataset info

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 26 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   student_id                       8000 non-null   int64
 1   age                              8000 non-null   int64
 2   gender                           8000 non-null   object
 3   grade_level                      8000 non-null   object
 4   study_hours_per_day              8000 non-null   float64
 5   uses_ai                          8000 non-null   int64
 6   ai_usage_time_minutes            8000 non-null   int64
 7   ai_tools_used                    6638 non-null   object
 8   ai_usage_purpose                 6654 non-null   object
 9   ai_dependency_score              8000 non-null   int64
 10  ai_generated_content_percentage  8000 non-null   int64
 11  ai_prompts_per_week              8000 non-null   int64
 12  ai_ethics_score                  8000 non-null   int64
 13  last_exam_score                  8000 non-null   int64
 14  assignment_scores_avg            8000 non-null   float64
 15  attendance_percentage            8000 non-null   float64
 16  concept_understanding_score      8000 non-null   int64
 17  study_consistency_index          8000 non-null   float64
 18  improvement_rate                 8000 non-null   float64
 19  sleep_hours                      8000 non-null   float64
 20  social_media_hours               8000 non-null   float64
 21  tutoring_hours                   8000 non-null   float64
 22  class_participation_score        8000 non-null   int64
 23  final_score                      8000 non-null   float64
 24  passed                           8000 non-null   int64
 25  performance_category             8000 non-null   object
dtypes: float64(9), int64(12), object(5)
memory usage: 1.6+ MB

## Q8. Summary statistics

In [ ]:
df.describe()

,student_id,age,study_hours_per_day,uses_ai,ai_usage_time_minutes,ai_dependency_score,ai_generated_content_percentage,ai_prompts_per_week,ai_ethics_score,last_exam_score,...,attendance_percentage,concept_understanding_score,study_consistency_index,improvement_rate,sleep_hours,social_media_hours,tutoring_hours,class_participation_score,final_score,passed
count,8000.00000,8000.00000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,...,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000
mean,4000.50000,18.96725,3.286938,0.641000,88.989875,5.515125,50.057500,59.359500,5.472375,59.501250,...,69.852112,5.484750,5.516450,10.127325,6.465025,3.010600,2.523387,5.463375,56.811988,0.889250
std,2309.54541,3.15316,1.582171,0.479737,52.184077,2.883064,29.440109,34.869496,2.872067,23.161888,...,17.234339,2.898546,2.586377,17.479288,1.435670,1.744974,1.436991,2.881917,13.455724,0.313842
min,1.00000,14.00000,0.500000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,20.000000,...,40.000000,1.000000,1.000000,-20.000000,4.000000,0.000000,0.000000,1.000000,12.700000,0.000000
25%,2000.75000,16.00000,1.900000,0.000000,43.000000,3.000000,25.000000,29.000000,3.000000,39.750000,...,54.800000,3.000000,3.200000,-5.000000,5.200000,1.500000,1.300000,3.000000,47.300000,1.000000
50%,4000.50000,19.00000,3.300000,1.000000,89.000000,6.000000,50.000000,59.000000,6.000000,59.000000,...,70.000000,5.000000,5.500000,10.150000,6.400000,3.000000,2.500000,5.000000,56.900000,1.000000
75%,6000.25000,22.00000,4.600000,1.000000,134.000000,8.000000,76.000000,90.000000,8.000000,80.000000,...,84.600000,8.000000,7.800000,25.500000,7.700000,4.500000,3.800000,8.000000,66.200000,1.000000
max,8000.00000,24.00000,6.000000,1.000000,179.000000,10.000000,100.000000,119.000000,10.000000,99.000000,...,100.000000,10.000000,10.000000,40.000000,9.000000,6.000000,5.000000,10.000000,95.800000,1.000000

## Q9. Check data types

In [ ]:
df.dtypes

student_id                           int64
age                                  int64
gender                              object
grade_level                         object
study_hours_per_day                float64
uses_ai                              int64
ai_usage_time_minutes                int64
ai_tools_used                       object
ai_usage_purpose                    object
ai_dependency_score                  int64
ai_generated_content_percentage      int64
ai_prompts_per_week                  int64
ai_ethics_score                      int64
last_exam_score                      int64
assignment_scores_avg              float64
attendance_percentage              float64
concept_understanding_score          int64
study_consistency_index            float64
improvement_rate                   float64
sleep_hours                        float64
social_media_hours                 float64
tutoring_hours                     float64
class_participation_score            int64
final_score                        float64
passed                               int64
performance_category                object
dtype: object

## Q10. Count missing values

In [ ]:
df.isnull().sum()

student_id                            0
age                                   0
gender                                0
grade_level                           0
study_hours_per_day                   0
uses_ai                               0
ai_usage_time_minutes                 0
ai_tools_used                      1362
ai_usage_purpose                   1346
ai_dependency_score                   0
ai_generated_content_percentage       0
ai_prompts_per_week                   0
ai_ethics_score                       0
last_exam_score                       0
assignment_scores_avg                 0
attendance_percentage                 0
concept_understanding_score           0
study_consistency_index               0
improvement_rate                      0
sleep_hours                           0
social_media_hours                    0
tutoring_hours                        0
class_participation_score             0
final_score                           0
passed                                0
performance_category                  0
dtype: int64

## Q11. Count duplicates

In [ ]:
df.duplicated().sum()

np.int64(0)

## Q12. Remove duplicates

In [ ]:
df.drop_duplicates()

,student_id,age,gender,grade_level,study_hours_per_day,uses_ai,ai_usage_time_minutes,ai_tools_used,ai_usage_purpose,ai_dependency_score,...,concept_understanding_score,study_consistency_index,improvement_rate,sleep_hours,social_media_hours,tutoring_hours,class_participation_score,final_score,passed,performance_category
0,1,20,Female,1st Year,2.5,1,170,NaN,Exam Prep,10,...,4,9.0,8.1,7.2,1.5,4.6,6,36.8,0,Low
1,2,17,Male,12th,3.4,1,123,NaN,Notes,4,...,8,8.5,13.8,7.6,5.1,2.7,6,65.5,1,Medium
2,3,24,Male,3rd Year,0.8,0,35,Copilot,Doubt Solving,8,...,7,2.1,39.1,5.7,0.2,4.0,3,66.3,1,Medium
3,4,21,Female,12th,4.4,0,45,ChatGPT+Gemini,Notes,3,...,5,6.7,25.2,8.2,4.2,2.9,2,69.5,1,Medium
4,5,18,Other,3rd Year,3.5,1,21,ChatGPT+Gemini,Coding,2,...,5,5.4,2.7,8.7,0.2,2.9,2,49.7,1,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,7996,23,Male,3rd Year,3.0,0,178,Gemini,NaN,6,...,5,8.1,19.2,8.3,1.9,1.0,10,49.7,1,Low
7996,7997,21,Other,1st Year,3.3,0,63,Claude,Exam Prep,10,...,6,5.7,3.0,5.0,1.3,2.9,5,58.4,1,Medium
7997,7998,24,Male,3rd Year,1.6,0,113,ChatGPT,Coding,5,...,6,4.5,-18.0,5.0,3.5,0.1,9,69.1,1,Medium
7998,7999,22,Female,2nd Year,5.5,0,21,Copilot,Coding,5,...,8,3.4,-19.1,4.7,5.9,0.4,7,49.2,1,Low
7999,8000,15,Male,12th,4.6,0,42,NaN,NaN,9,...,6,9.7,-4.9,9.0,2.9,2.1,5,69.7,1,Medium

## Q13. Unique values in performance_category

In [ ]:
df['performance_category'].unique()

array(['Low', 'Medium', 'High'], dtype=object)

## Q14. Value counts

In [15]:
df['performance_category'].value_counts()

performance_category
Medium    4705
Low       2542
High       753
Name: count, dtype: int64

## Q15. Mean final score

In [ ]:
df['final_score'].mean()

np.float64(56.8119875)

## Q16. Median final score

In [ ]:
df['final_score'].median()

56.9

## Q17. Maximum final score

In [ ]:
df['final_score'].max()

95.8

## Q18. Minimum final score

In [ ]:
df['final_score'].min()

12.7

## Q19. Students passed

In [16]:
df[df['passed']==1]

,student_id,age,gender,grade_level,study_hours_per_day,uses_ai,ai_usage_time_minutes,ai_tools_used,ai_usage_purpose,ai_dependency_score,...,concept_understanding_score,study_consistency_index,improvement_rate,sleep_hours,social_media_hours,tutoring_hours,class_participation_score,final_score,passed,performance_category
1,2,17,Male,12th,3.4,1,123,NaN,Notes,4,...,8,8.5,13.8,7.6,5.1,2.7,6,65.5,1,Medium
2,3,24,Male,3rd Year,0.8,0,35,Copilot,Doubt Solving,8,...,7,2.1,39.1,5.7,0.2,4.0,3,66.3,1,Medium
3,4,21,Female,12th,4.4,0,45,ChatGPT+Gemini,Notes,3,...,5,6.7,25.2,8.2,4.2,2.9,2,69.5,1,Medium
4,5,18,Other,3rd Year,3.5,1,21,ChatGPT+Gemini,Coding,2,...,5,5.4,2.7,8.7,0.2,2.9,2,49.7,1,Low
5,6,20,Male,1st Year,5.1,1,34,Copilot,Coding,10,...,9,8,13.4,5.5,3.7,2.1,4,77.9,1,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,7996,23,Male,3rd Year,3.0,0,178,Gemini,NaN,6,...,5,8.1,19.2,8.3,1.9,1.0,10,49.7,1,Low
7996,7997,21,Other,1st Year,3.3,0,63,Claude,Exam Prep,10,...,6,5.7,3.0,5.0,1.3,2.9,5,58.4,1,Medium
7997,7998,24,Male,3rd Year,1.6,0,113,ChatGPT,Coding,5,...,6,4.5,-18.0,5.0,3.5,0.1,9,69.1,1,Medium
7998,7999,22,Female,2nd Year,5.5,0,21,Copilot,Coding,5,...,8,3.4,-19.1,4.7,5.9,0.4,7,49.2,1,Low
7999,8000,15,Male,12th,4.6,0,42,NaN,NaN,9,...,6,9.7,-4.9,9.0,2.9,2.1,5,69.7,1,Medium

## Q20. Average attendance

In [ ]:
df['attendance_percentage'].mean()

np.float64(69.85211249999999)

## Q21. Correlation matrix

In [ ]:
df.corr(numeric_only=True)

,student_id,age,study_hours_per_day,uses_ai,ai_usage_time_minutes,ai_dependency_score,ai_generated_content_percentage,ai_prompts_per_week,ai_ethics_score,last_exam_score,...,attendance_percentage,concept_understanding_score,study_consistency_index,improvement_rate,sleep_hours,social_media_hours,tutoring_hours,class_participation_score,final_score,passed
student_id,1.000000,0.016347,-0.018194,0.020702,0.013013,0.025216,-0.014774,0.018575,0.005220,-0.001756,...,0.009116,0.007137,-0.002508,-0.000017,0.003736,0.013393,0.006234,0.000127,0.003917,-0.002300
age,0.016347,1.000000,-0.020504,0.006359,-0.004758,-0.002380,-0.003763,-0.034365,-0.013394,0.010088,...,-0.016043,0.002243,-0.009601,-0.009307,0.017010,0.000906,0.003041,0.000212,0.007615,0.008083
study_hours_per_day,-0.018194,-0.020504,1.000000,-0.009835,0.002130,0.004208,0.003263,0.000951,0.002007,0.009136,...,0.002556,0.011669,-0.013398,-0.020131,0.019018,-0.007792,-0.012015,0.006148,0.015798,0.009423
uses_ai,0.020702,0.006359,-0.009835,1.000000,-0.008734,0.009530,-0.011329,0.008755,-0.007562,0.004980,...,0.016414,-0.003848,0.015843,0.007505,0.011917,0.019540,0.004709,-0.021628,-0.001628,0.004921
ai_usage_time_minutes,0.013013,-0.004758,0.002130,-0.008734,1.000000,-0.002033,0.017965,-0.001524,0.008217,-0.015640,...,0.013681,0.006915,0.001909,-0.016563,0.004734,0.004804,-0.001091,-0.007230,-0.001610,0.004031
ai_dependency_score,0.025216,-0.002380,0.004208,0.009530,-0.002033,1.000000,-0.009596,-0.007407,-0.013387,0.011436,...,0.012207,0.018077,0.012489,0.001123,-0.007909,0.008323,-0.016312,-0.017598,0.014077,0.008622
ai_generated_content_percentage,-0.014774,-0.003763,0.003263,-0.011329,0.017965,-0.009596,1.000000,-0.002095,0.022763,0.017855,...,0.014436,0.021773,-0.005647,0.022501,-0.009494,-0.008901,-0.003344,0.002312,-0.096552,-0.073634
ai_prompts_per_week,0.018575,-0.034365,0.000951,0.008755,-0.001524,-0.007407,-0.002095,1.000000,0.012410,0.000871,...,0.008894,-0.003706,-0.006162,-0.014216,0.005252,0.014999,0.000342,-0.003628,-0.010148,0.001103
ai_ethics_score,0.005220,-0.013394,0.002007,-0.007562,0.008217,-0.013387,0.022763,0.012410,1.000000,0.006816,...,-0.008723,0.007420,-0.022646,0.008076,0.009240,-0.003095,0.007664,-0.001240,0.013269,0.016439
last_exam_score,-0.001756,0.010088,0.009136,0.004980,-0.015640,0.011436,0.017855,0.000871,0.006816,1.000000,...,0.004183,-0.008204,-0.006623,-0.002291,-0.015300,-0.004504,-0.005766,0.004300,0.681675,0.380268
assignment_scores_avg,0.000307,-0.008140,-0.007500,-0.011901,0.009731,0.001983,-0.002759,-0.001409,0.012843,0.006272,...,-0.002236,0.009071,-0.012190,0.011945,0.001317,0.016712,-0.006291,0.002806,0.454554,0.288267
attendance_percentage,0.009116,-0.016043,0.002556,0.016414,0.013681,0.012207,0.014436,0.008894,-0.008723,0.004183,...,1.000000,0.012883,-0.016864,0.007846,0.016681,-0.008377,0.024523,0.002348,-0.005182,0.004458
concept_understanding_score,0.007137,0.002243,0.011669,-0.003848,0.006915,0.018077,0.021773,-0.003706,0.007420,-0.008204,...,0.012883,1.000000,-0.005273,0.004212,-0.001357,-0.002598,0.013170,-0.005687,0.423874,0.256232
study_consistency_index,-0.002508,-0.009601,-0.013398,0.015843,0.001909,0.012489,-0.005647,-0.006162,-0.022646,-0.006623,...,-0.016864,-0.005273,1.000000,-0.012914,0.012249,0.009978,-0.008038,0.011942,-0.014126,-0.020734
improvement_rate,-0.000017,-0.009307,-0.020131,0.007505,-0.016563,0.001123,0.022501,-0.014216,0.008076,-0.002291,...,0.007846,0.004212,-0.012914,1.000000,0.009338,0.004395,-0.003798,-0.022319,-0.001549,-0.001281
sleep_hours,0.003736,0.017010,0.019018,0.011917,0.004734,-0.007909,-0.009494,0.005252,0.009240,-0.015300,...,0.016681,-0.001357,0.012249,0.009338,1.000000,-0.002764,0.008812,-0.017336,-0.005785,0.006385
social_media_hours,0.013393,0.000906,-0.007792,0.019540,0.004804,0.008323,-0.008901,0.014999,-0.003095,-0.004504,...,-0.008377,-0.002598,0.009978,0.004395,-0.002764,1.000000,-0.008496,-0.002384,0.004099,0.006983
tutoring_hours,0.006234,0.003041,-0.012015,0.004709,-0.001091,-0.016312,-0.003344,0.000342,0.007664,-0.005766,...,0.024523,0.013170,-0.008038,-0.003798,0.008812,-0.008496,1.000000,0.000869,-0.008564,-0.010001
class_participation_score,0.000127,0.000212,0.006148,-0.021628,-0.007230,-0.017598,0.002312,-0.003628,-0.001240,0.004300,...,0.002348,-0.005687,0.011942,-0.022319,-0.017336,-0.002384,0.000869,1.000000,0.003523,0.010028
final_score,0.003917,0.007615,0.015798,-0.001628,-0.001610,0.014077,-0.096552,-0.010148,0.013269,0.681675,...,-0.005182,0.423874,-0.014126,-0.001549,-0.005785,0.004099,-0.008564,0.003523,1.000000,0.592637
passed,-0.002300,0.008083,0.009423,0.004921,0.004031,0.008622,-0.073634,0.001103,0.016439,0.380268,...,0.004458,0.256232,-0.020734,-0.001281,0.006385,0.006983,-0.010001,0.010028,0.592637,1.000000

## Q22. Group by learner type

In [ ]:
df.groupby('performance_category')['final_score'].mean()

performance_category
High      80.696547
Low       41.540637
Medium    61.240191
Name: final_score, dtype: float64

## Q23. Sort by final score desc

In [ ]:
df.sort_values('final_score', ascending=False)

,student_id,age,gender,grade_level,study_hours_per_day,uses_ai,ai_usage_time_minutes,ai_tools_used,ai_usage_purpose,ai_dependency_score,...,concept_understanding_score,study_consistency_index,improvement_rate,sleep_hours,social_media_hours,tutoring_hours,class_participation_score,final_score,passed,performance_category
7719,7720,21,Female,11th,0.7,1,130,ChatGPT,Coding,7,...,10,4.7,19.7,5.0,0.1,1.5,10,95.8,1,High
7980,7981,22,Male,10th,4.9,1,42,Gemini,Doubt Solving,6,...,10,4.2,26.1,5.5,3.9,1.5,2,94.8,1,High
4028,4029,24,Female,10th,2.1,1,65,Copilot,Notes,2,...,7,3.5,-19.3,6.3,2.0,2.6,5,94.4,1,High
1863,1864,23,Female,2nd Year,4.7,1,107,Gemini,Doubt Solving,9,...,10,6.7,14.6,7.7,3.1,5.0,10,94.3,1,High
5302,5303,24,Male,10th,5.0,1,116,Gemini,Coding,3,...,10,7.6,-7.7,5.7,0.4,1.4,6,94.1,1,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4529,4530,19,Male,3rd Year,5.6,1,171,NaN,Notes,5,...,1,8.9,26.7,6.1,0.8,3.5,6,20.3,0,Low
2183,2184,20,Male,12th,0.8,1,166,Copilot,Notes,5,...,1,5.3,-9.5,8.8,3.6,1.3,8,18.3,0,Low
6082,6083,16,Male,11th,4.9,0,33,ChatGPT,Notes,6,...,2,2.0,33.0,5.0,5.0,3.8,7,16.3,0,Low
3328,3329,24,Male,1st Year,5.4,1,141,Gemini,NaN,6,...,1,7.0,34.1,4.8,2.4,1.9,5,15.4,0,Low
785,786,24,Female,12th,3.4,1,23,ChatGPT+Gemini,Doubt Solving,7,...,1,8.2,9.4,6.5,0.7,1.6,10,12.7,0,Low

## Q24. Top 10 performers

In [ ]:
# Method 1
# df.nlargest(10,'final_score')

#Method 2
df.sort_values("final_score", ascending=False).head(10)

,student_id,age,gender,grade_level,study_hours_per_day,uses_ai,ai_usage_time_minutes,ai_tools_used,ai_usage_purpose,ai_dependency_score,...,concept_understanding_score,study_consistency_index,improvement_rate,sleep_hours,social_media_hours,tutoring_hours,class_participation_score,final_score,passed,performance_category
7719,7720,21,Female,11th,0.7,1,130,ChatGPT,Coding,7,...,10,4.7,19.7,5.0,0.1,1.5,10,95.8,1,High
7980,7981,22,Male,10th,4.9,1,42,Gemini,Doubt Solving,6,...,10,4.2,26.1,5.5,3.9,1.5,2,94.8,1,High
4028,4029,24,Female,10th,2.1,1,65,Copilot,Notes,2,...,7,3.5,-19.3,6.3,2.0,2.6,5,94.4,1,High
1863,1864,23,Female,2nd Year,4.7,1,107,Gemini,Doubt Solving,9,...,10,6.7,14.6,7.7,3.1,5.0,10,94.3,1,High
5302,5303,24,Male,10th,5.0,1,116,Gemini,Coding,3,...,10,7.6,-7.7,5.7,0.4,1.4,6,94.1,1,High
5229,5230,15,Male,3rd Year,4.9,1,167,Claude,Exam Prep,5,...,8,5.9,19.0,4.8,0.2,1.6,2,93.8,1,High
2160,2161,18,Female,3rd Year,4.1,1,99,ChatGPT+Gemini,Homework,5,...,10,4.7,32.7,5.7,1.9,1.3,6,93.5,1,High
5477,5478,20,Male,11th,1.5,1,71,Copilot,Exam Prep,9,...,10,6.7,11.1,8.2,3.7,2.5,5,93.4,1,High
6497,6498,21,Female,10th,4.3,1,168,ChatGPT+Gemini,Coding,4,...,7,1.7,33.3,5.6,3.7,2.0,1,93.2,1,High
7011,7012,23,Male,1st Year,3.6,1,28,Gemini,Doubt Solving,4,...,10,5.7,32.2,7.7,5.8,1.0,8,93.1,1,High

## Q25. Bottom 10 performers

In [ ]:
#Method 1
# df.nsmallest(10,'final_score')

#Method 2
df.sort_values("final_score", ascending=True).head(10)

,student_id,age,gender,grade_level,study_hours_per_day,uses_ai,ai_usage_time_minutes,ai_tools_used,ai_usage_purpose,ai_dependency_score,...,concept_understanding_score,study_consistency_index,improvement_rate,sleep_hours,social_media_hours,tutoring_hours,class_participation_score,final_score,passed,performance_category
785,786,24,Female,12th,3.4,1,23,ChatGPT+Gemini,Doubt Solving,7,...,1,8.2,9.4,6.5,0.7,1.6,10,12.7,0,Low
3328,3329,24,Male,1st Year,5.4,1,141,Gemini,NaN,6,...,1,7.0,34.1,4.8,2.4,1.9,5,15.4,0,Low
6082,6083,16,Male,11th,4.9,0,33,ChatGPT,Notes,6,...,2,2.0,33.0,5.0,5.0,3.8,7,16.3,0,Low
2183,2184,20,Male,12th,0.8,1,166,Copilot,Notes,5,...,1,5.3,-9.5,8.8,3.6,1.3,8,18.3,0,Low
6642,6643,23,Female,12th,1.3,1,98,ChatGPT,Coding,8,...,2,8.4,4.6,4.7,2.0,1.7,1,20.3,0,Low
4529,4530,19,Male,3rd Year,5.6,1,171,NaN,Notes,5,...,1,8.9,26.7,6.1,0.8,3.5,6,20.3,0,Low
5160,5161,23,Male,2nd Year,4.2,1,115,ChatGPT,Notes,10,...,4,6.6,-13.2,6.1,2.1,3.3,1,20.6,0,Low
5495,5496,19,Female,1st Year,0.7,0,68,Copilot,Exam Prep,2,...,1,2.8,8.9,5.0,3.6,4.6,5,20.8,0,Low
7982,7983,20,Male,12th,5.4,1,172,ChatGPT,NaN,6,...,1,7.5,-1.1,4.9,0.0,2.2,6,21.1,0,Low
2066,2067,24,Female,2nd Year,2.6,0,81,Copilot,NaN,4,...,1,8.0,15.3,7.5,2.1,4.8,4,21.1,0,Low